{{- if or .Values.secret.twitch.createSecret .Values.secret.django.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "django-learn.fullname" . }}
  labels:
    {{- include "django-learn.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secret.twitch.createSecret }}
  {{ .Values.secret.twitch.clientIdKey }}: {{ default "" .Values.secret.twitch.clientId | b64enc | quote }}
  {{ .Values.secret.twitch.clientSecretKey }}: {{ default "" .Values.secret.twitch.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secret.django.createSecret }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "django-learn.fullname" .)) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $secretKey := default (get $secretData .Values.secret.django.secretKeyKey) (.Values.secret.django.secretKey | b64enc) }}
  {{ .Values.secret.django.secretKeyKey }}: {{ default (randAlphaNum 32 | b64enc) $secretKey | quote }}
  {{- end }}
{{- end }}
